import test
# 'print a' will result in an exception
print test.a
